# Generated by Django 5.2.8 on 2025-11-23 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_bio_member_created_at_member_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
